[target.x86_64-pc-windows-msvc]
# Je conserve la protection du flux de contrôle et intègre le runtime C au binaire portable.
rustflags = ["-C", "control-flow-guard=yes", "-C", "target-feature=+crt-static"]
